In [ ]:
import pandas as pd

In [ ]:
items = pd.read_csv('items.csv')
ratings = pd.read_csv('ratings.csv')

In [ ]:
items.head()

,product,category,product_urls,search_links
0,8870b0d384138a81cfdc91f98d1dde9b,Apparel & Accessories|Shoes,http://i.pinimg.com/400x/88/70/b0/8870b0d38413...,https://lens.google.com/uploadbyurl?url=http:/...
1,70d392390fa258ba9b5d6b83ea29857e,Apparel & Accessories|Shoes,http://i.pinimg.com/400x/70/d3/92/70d392390fa2...,https://lens.google.com/uploadbyurl?url=http:/...
2,2c05db9ff1abbcfc4bfd50dd003aac80,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/2c/05/db/2c05db9ff1ab...,https://lens.google.com/uploadbyurl?url=http:/...
3,2b2cc3a8b588b7282be0511568b51ee7,Apparel & Accessories|Clothing|Shirts & Tops,http://i.pinimg.com/400x/2b/2c/c3/2b2cc3a8b588...,https://lens.google.com/uploadbyurl?url=http:/...
4,a141ed588bdaeccf1f695889a5aa7085,Apparel & Accessories|Clothing|Shorts,http://i.pinimg.com/400x/a1/41/ed/a141ed588bda...,https://lens.google.com/uploadbyurl?url=http:/...

In [ ]:
ratings.head()

   UserID                         ProductID  Rating
0   82402  492f8a4f803d462886b9667b8b24df6b     5.0
1  167933  bac58a08fa8e1dddc7c1ef6d75ff506b     2.0
2    6094  8545d3fb7c612071939c62fdc99cd921     4.0
3   74978  3caa3cddbfdd9d14428d808a0752c2c5     2.0
4   72211  903907b95752a9eaa1ad88461fb4ec98     3.0

In [ ]:
ratings = pd.merge(ratings,items,left_on='ProductID',right_on='product')

In [ ]:
ratings.head()

,UserID,ProductID,Rating,product,category,product_urls,search_links
0,82402,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/49/2f/8a/492f8a4f803d...,https://lens.google.com/uploadbyurl?url=http:/...
1,178978,492f8a4f803d462886b9667b8b24df6b,2.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/49/2f/8a/492f8a4f803d...,https://lens.google.com/uploadbyurl?url=http:/...
2,123426,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/49/2f/8a/492f8a4f803d...,https://lens.google.com/uploadbyurl?url=http:/...
3,181540,492f8a4f803d462886b9667b8b24df6b,2.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/49/2f/8a/492f8a4f803d...,https://lens.google.com/uploadbyurl?url=http:/...
4,53693,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants,http://i.pinimg.com/400x/49/2f/8a/492f8a4f803d...,https://lens.google.com/uploadbyurl?url=http:/...

In [ ]:
ratings.describe()

              UserID        Rating
count  883636.000000  883636.00000
mean    93098.585470       3.90694
std     53733.322812       1.41828
min         1.000000       1.00000
25%     46546.000000       3.00000
50%     93128.000000       5.00000
75%    139627.000000       5.00000
max    186190.000000       5.00000

In [ ]:
ratings.drop(['product_urls','search_links'],axis = 1, inplace=True)

In [ ]:
ratings.head()

,UserID,ProductID,Rating,product,category
0,82402,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants
1,178978,492f8a4f803d462886b9667b8b24df6b,2.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants
2,123426,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants
3,181540,492f8a4f803d462886b9667b8b24df6b,2.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants
4,53693,492f8a4f803d462886b9667b8b24df6b,5.0,492f8a4f803d462886b9667b8b24df6b,Apparel & Accessories|Clothing|Pants

In [ ]:
grouped_products = ratings.groupby('')

In [ ]:
grouped_products.groups.keys()

dict_keys(['Apparel & Accessories|Clothing Accessories|Sunglasses', 'Apparel & Accessories|Clothing|Outerwear|Coats & Jackets', 'Apparel & Accessories|Clothing|Pants', 'Apparel & Accessories|Clothing|Shirts & Tops', 'Apparel & Accessories|Clothing|Shorts', 'Apparel & Accessories|Clothing|Skirts', 'Apparel & Accessories|Handbags, Wallets & Cases', 'Apparel & Accessories|Jewelry|Earrings', 'Apparel & Accessories|Jewelry|Necklaces', 'Apparel & Accessories|Shoes'])

In [ ]:
for key in grouped_products.groups.keys():
  temp_df = grouped_products.get_group(key)
  result = temp_df.groupby('ProductID')['Rating'].mean()
  result_df = pd.DataFrame({'ProductID':result.index, 'Mean Rating':result.values})
  result_df = result_df.sort_values('Mean Rating',ascending=False)
  key_word_list = key.split("|")
  result_df.to_csv(key_word_list[-1]+'.csv',index=False)